default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: uwc-shop_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: uwc-shop_test

production:
  <<: *default
  database: uwc-shop_production
  username: uwc-shop
  password: <%= ENV['UWC-SHOP_DATABASE_PASSWORD'] %>
